github:
  homepage: https://echarts.apache.org/
  labels:
    - echarts
    - data-visualization
    - charts
    - charting-library
    - visualization
    - apache
    - data-viz
    - canvas
    - svg
